#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinhVien
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLySinhVien")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertThong_Tin_Nguoi_LH_GV(Thong_Tin_Nguoi_LH_GV instance);
    partial void UpdateThong_Tin_Nguoi_LH_GV(Thong_Tin_Nguoi_LH_GV instance);
    partial void DeleteThong_Tin_Nguoi_LH_GV(Thong_Tin_Nguoi_LH_GV instance);
    partial void InsertThong_Tin_Nguoi_LH(Thong_Tin_Nguoi_LH instance);
    partial void UpdateThong_Tin_Nguoi_LH(Thong_Tin_Nguoi_LH instance);
    partial void DeleteThong_Tin_Nguoi_LH(Thong_Tin_Nguoi_LH instance);
    partial void InsertThong_Tin_Lien_Lac_GV(Thong_Tin_Lien_Lac_GV instance);
    partial void UpdateThong_Tin_Lien_Lac_GV(Thong_Tin_Lien_Lac_GV instance);
    partial void DeleteThong_Tin_Lien_Lac_GV(Thong_Tin_Lien_Lac_GV instance);
    partial void InsertThong_Tin_Lien_Lac(Thong_Tin_Lien_Lac instance);
    partial void UpdateThong_Tin_Lien_Lac(Thong_Tin_Lien_Lac instance);
    partial void DeleteThong_Tin_Lien_Lac(Thong_Tin_Lien_Lac instance);
    partial void InsertThong_Tin_Khoa_Hoc(Thong_Tin_Khoa_Hoc instance);
    partial void UpdateThong_Tin_Khoa_Hoc(Thong_Tin_Khoa_Hoc instance);
    partial void DeleteThong_Tin_Khoa_Hoc(Thong_Tin_Khoa_Hoc instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertPhongHoc(PhongHoc instance);
    partial void UpdatePhongHoc(PhongHoc instance);
    partial void DeletePhongHoc(PhongHoc instance);
    partial void InsertMonHoc(MonHoc instance);
    partial void UpdateMonHoc(MonHoc instance);
    partial void DeleteMonHoc(MonHoc instance);
    partial void InsertLop(Lop instance);
    partial void UpdateLop(Lop instance);
    partial void DeleteLop(Lop instance);
    partial void InsertKhoa(Khoa instance);
    partial void UpdateKhoa(Khoa instance);
    partial void DeleteKhoa(Khoa instance);
    partial void InsertDiem(Diem instance);
    partial void UpdateDiem(Diem instance);
    partial void DeleteDiem(Diem instance);
    partial void InsertThong_Tin_Sinh_Vien(Thong_Tin_Sinh_Vien instance);
    partial void UpdateThong_Tin_Sinh_Vien(Thong_Tin_Sinh_Vien instance);
    partial void DeleteThong_Tin_Sinh_Vien(Thong_Tin_Sinh_Vien instance);
    partial void InsertGiangVien(GiangVien instance);
    partial void UpdateGiangVien(GiangVien instance);
    partial void DeleteGiangVien(GiangVien instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::SinhVien.Properties.Settings.Default.QuanLySinhVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Thong_Tin_Nguoi_LH_GV> Thong_Tin_Nguoi_LH_GVs
		{
			get
			{
				return this.GetTable<Thong_Tin_Nguoi_LH_GV>();
			}
		}
		
		public System.Data.Linq.Table<Thong_Tin_Nguoi_LH> Thong_Tin_Nguoi_LHs
		{
			get
			{
				return this.GetTable<Thong_Tin_Nguoi_LH>();
			}
		}
		
		public System.Data.Linq.Table<Thong_Tin_Lien_Lac_GV> Thong_Tin_Lien_Lac_GVs
		{
			get
			{
				return this.GetTable<Thong_Tin_Lien_Lac_GV>();
			}
		}
		
		public System.Data.Linq.Table<Thong_Tin_Lien_Lac> Thong_Tin_Lien_Lacs
		{
			get
			{
				return this.GetTable<Thong_Tin_Lien_Lac>();
			}
		}
		
		public System.Data.Linq.Table<Thong_Tin_Khoa_Hoc> Thong_Tin_Khoa_Hocs
		{
			get
			{
				return this.GetTable<Thong_Tin_Khoa_Hoc>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<PhongHoc> PhongHocs
		{
			get
			{
				return this.GetTable<PhongHoc>();
			}
		}
		
		public System.Data.Linq.Table<MonHoc> MonHocs
		{
			get
			{
				return this.GetTable<MonHoc>();
			}
		}
		
		public System.Data.Linq.Table<Lop> Lops
		{
			get
			{
				return this.GetTable<Lop>();
			}
		}
		
		public System.Data.Linq.Table<Khoa> Khoas
		{
			get
			{
				return this.GetTable<Khoa>();
			}
		}
		
		public System.Data.Linq.Table<Diem> Diems
		{
			get
			{
				return this.GetTable<Diem>();
			}
		}
		
		public System.Data.Linq.Table<Thong_Tin_Sinh_Vien> Thong_Tin_Sinh_Viens
		{
			get
			{
				return this.GetTable<Thong_Tin_Sinh_Vien>();
			}
		}
		
		public System.Data.Linq.Table<GiangVien> GiangViens
		{
			get
			{
				return this.GetTable<GiangVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thong_Tin_Nguoi_LH_GV")]
	public partial class Thong_Tin_Nguoi_LH_GV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGV;
		
		private string _HoTenLienHe;
		
		private string _DiaChiLienHe;
		
		private string _DienThoaiLienHe;
		
		private EntityRef<GiangVien> _GiangVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGVChanging(int value);
    partial void OnMaGVChanged();
    partial void OnHoTenLienHeChanging(string value);
    partial void OnHoTenLienHeChanged();
    partial void OnDiaChiLienHeChanging(string value);
    partial void OnDiaChiLienHeChanged();
    partial void OnDienThoaiLienHeChanging(string value);
    partial void OnDienThoaiLienHeChanged();
    #endregion
		
		public Thong_Tin_Nguoi_LH_GV()
		{
			this._GiangVien = default(EntityRef<GiangVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaGV
		{
			get
			{
				return this._MaGV;
			}
			set
			{
				if ((this._MaGV != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGVChanging(value);
					this.SendPropertyChanging();
					this._MaGV = value;
					this.SendPropertyChanged("MaGV");
					this.OnMaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenLienHe", DbType="NVarChar(10)")]
		public string HoTenLienHe
		{
			get
			{
				return this._HoTenLienHe;
			}
			set
			{
				if ((this._HoTenLienHe != value))
				{
					this.OnHoTenLienHeChanging(value);
					this.SendPropertyChanging();
					this._HoTenLienHe = value;
					this.SendPropertyChanged("HoTenLienHe");
					this.OnHoTenLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiLienHe", DbType="NVarChar(10)")]
		public string DiaChiLienHe
		{
			get
			{
				return this._DiaChiLienHe;
			}
			set
			{
				if ((this._DiaChiLienHe != value))
				{
					this.OnDiaChiLienHeChanging(value);
					this.SendPropertyChanging();
					this._DiaChiLienHe = value;
					this.SendPropertyChanged("DiaChiLienHe");
					this.OnDiaChiLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiLienHe", DbType="NVarChar(10)")]
		public string DienThoaiLienHe
		{
			get
			{
				return this._DienThoaiLienHe;
			}
			set
			{
				if ((this._DienThoaiLienHe != value))
				{
					this.OnDienThoaiLienHeChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiLienHe = value;
					this.SendPropertyChanged("DienThoaiLienHe");
					this.OnDienThoaiLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_Thong_Tin_Nguoi_LH_GV", Storage="_GiangVien", ThisKey="MaGV", OtherKey="MaGV", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.Thong_Tin_Nguoi_LH_GV = null;
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Nguoi_LH_GV = this;
						this._MaGV = value.MaGV;
					}
					else
					{
						this._MaGV = default(int);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thong_Tin_Nguoi_LH")]
	public partial class Thong_Tin_Nguoi_LH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MaSV;
		
		private string _HoTenLienHe;
		
		private string _DiaChiLienHe;
		
		private string _DienThoaiLienHe;
		
		private string _HoTenCha;
		
		private string _DienThoaiCha;
		
		private string _HoTenMe;
		
		private string _DienThoaiMe;
		
		private EntityRef<Thong_Tin_Sinh_Vien> _Thong_Tin_Sinh_Vien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnHoTenLienHeChanging(string value);
    partial void OnHoTenLienHeChanged();
    partial void OnDiaChiLienHeChanging(string value);
    partial void OnDiaChiLienHeChanged();
    partial void OnDienThoaiLienHeChanging(string value);
    partial void OnDienThoaiLienHeChanged();
    partial void OnHoTenChaChanging(string value);
    partial void OnHoTenChaChanged();
    partial void OnDienThoaiChaChanging(string value);
    partial void OnDienThoaiChaChanged();
    partial void OnHoTenMeChanging(string value);
    partial void OnHoTenMeChanged();
    partial void OnDienThoaiMeChanging(string value);
    partial void OnDienThoaiMeChanged();
    #endregion
		
		public Thong_Tin_Nguoi_LH()
		{
			this._Thong_Tin_Sinh_Vien = default(EntityRef<Thong_Tin_Sinh_Vien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					if (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenLienHe", DbType="NVarChar(10)")]
		public string HoTenLienHe
		{
			get
			{
				return this._HoTenLienHe;
			}
			set
			{
				if ((this._HoTenLienHe != value))
				{
					this.OnHoTenLienHeChanging(value);
					this.SendPropertyChanging();
					this._HoTenLienHe = value;
					this.SendPropertyChanged("HoTenLienHe");
					this.OnHoTenLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiLienHe", DbType="NVarChar(10)")]
		public string DiaChiLienHe
		{
			get
			{
				return this._DiaChiLienHe;
			}
			set
			{
				if ((this._DiaChiLienHe != value))
				{
					this.OnDiaChiLienHeChanging(value);
					this.SendPropertyChanging();
					this._DiaChiLienHe = value;
					this.SendPropertyChanged("DiaChiLienHe");
					this.OnDiaChiLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiLienHe", DbType="NVarChar(10)")]
		public string DienThoaiLienHe
		{
			get
			{
				return this._DienThoaiLienHe;
			}
			set
			{
				if ((this._DienThoaiLienHe != value))
				{
					this.OnDienThoaiLienHeChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiLienHe = value;
					this.SendPropertyChanged("DienThoaiLienHe");
					this.OnDienThoaiLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenCha", DbType="NVarChar(10)")]
		public string HoTenCha
		{
			get
			{
				return this._HoTenCha;
			}
			set
			{
				if ((this._HoTenCha != value))
				{
					this.OnHoTenChaChanging(value);
					this.SendPropertyChanging();
					this._HoTenCha = value;
					this.SendPropertyChanged("HoTenCha");
					this.OnHoTenChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiCha", DbType="NVarChar(20)")]
		public string DienThoaiCha
		{
			get
			{
				return this._DienThoaiCha;
			}
			set
			{
				if ((this._DienThoaiCha != value))
				{
					this.OnDienThoaiChaChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiCha = value;
					this.SendPropertyChanged("DienThoaiCha");
					this.OnDienThoaiChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenMe", DbType="NVarChar(10)")]
		public string HoTenMe
		{
			get
			{
				return this._HoTenMe;
			}
			set
			{
				if ((this._HoTenMe != value))
				{
					this.OnHoTenMeChanging(value);
					this.SendPropertyChanging();
					this._HoTenMe = value;
					this.SendPropertyChanged("HoTenMe");
					this.OnHoTenMeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiMe", DbType="NVarChar(20)")]
		public string DienThoaiMe
		{
			get
			{
				return this._DienThoaiMe;
			}
			set
			{
				if ((this._DienThoaiMe != value))
				{
					this.OnDienThoaiMeChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiMe = value;
					this.SendPropertyChanged("DienThoaiMe");
					this.OnDienThoaiMeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Thong_Tin_Nguoi_LH", Storage="_Thong_Tin_Sinh_Vien", ThisKey="MaSV", OtherKey="MaSV", IsForeignKey=true)]
		public Thong_Tin_Sinh_Vien Thong_Tin_Sinh_Vien
		{
			get
			{
				return this._Thong_Tin_Sinh_Vien.Entity;
			}
			set
			{
				Thong_Tin_Sinh_Vien previousValue = this._Thong_Tin_Sinh_Vien.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Sinh_Vien.Entity = null;
						previousValue.Thong_Tin_Nguoi_LHs.Remove(this);
					}
					this._Thong_Tin_Sinh_Vien.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Nguoi_LHs.Add(this);
						this._MaSV = value.MaSV;
					}
					else
					{
						this._MaSV = default(string);
					}
					this.SendPropertyChanged("Thong_Tin_Sinh_Vien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thong_Tin_Lien_Lac_GV")]
	public partial class Thong_Tin_Lien_Lac_GV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGV;
		
		private string _QuocGia;
		
		private string _TinhThanh;
		
		private string _QuanHuyen;
		
		private string _Phuong;
		
		private string _DiaChi;
		
		private string _DiDong;
		
		private string _Email;
		
		private EntityRef<GiangVien> _GiangVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGVChanging(int value);
    partial void OnMaGVChanged();
    partial void OnQuocGiaChanging(string value);
    partial void OnQuocGiaChanged();
    partial void OnTinhThanhChanging(string value);
    partial void OnTinhThanhChanged();
    partial void OnQuanHuyenChanging(string value);
    partial void OnQuanHuyenChanged();
    partial void OnPhuongChanging(string value);
    partial void OnPhuongChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDiDongChanging(string value);
    partial void OnDiDongChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Thong_Tin_Lien_Lac_GV()
		{
			this._GiangVien = default(EntityRef<GiangVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaGV
		{
			get
			{
				return this._MaGV;
			}
			set
			{
				if ((this._MaGV != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGVChanging(value);
					this.SendPropertyChanging();
					this._MaGV = value;
					this.SendPropertyChanged("MaGV");
					this.OnMaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocGia", DbType="NVarChar(20)")]
		public string QuocGia
		{
			get
			{
				return this._QuocGia;
			}
			set
			{
				if ((this._QuocGia != value))
				{
					this.OnQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._QuocGia = value;
					this.SendPropertyChanged("QuocGia");
					this.OnQuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhThanh", DbType="NVarChar(20)")]
		public string TinhThanh
		{
			get
			{
				return this._TinhThanh;
			}
			set
			{
				if ((this._TinhThanh != value))
				{
					this.OnTinhThanhChanging(value);
					this.SendPropertyChanging();
					this._TinhThanh = value;
					this.SendPropertyChanged("TinhThanh");
					this.OnTinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuanHuyen", DbType="NVarChar(20)")]
		public string QuanHuyen
		{
			get
			{
				return this._QuanHuyen;
			}
			set
			{
				if ((this._QuanHuyen != value))
				{
					this.OnQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._QuanHuyen = value;
					this.SendPropertyChanged("QuanHuyen");
					this.OnQuanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phuong", DbType="NVarChar(20)")]
		public string Phuong
		{
			get
			{
				return this._Phuong;
			}
			set
			{
				if ((this._Phuong != value))
				{
					this.OnPhuongChanging(value);
					this.SendPropertyChanging();
					this._Phuong = value;
					this.SendPropertyChanged("Phuong");
					this.OnPhuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiDong", DbType="NVarChar(20)")]
		public string DiDong
		{
			get
			{
				return this._DiDong;
			}
			set
			{
				if ((this._DiDong != value))
				{
					this.OnDiDongChanging(value);
					this.SendPropertyChanging();
					this._DiDong = value;
					this.SendPropertyChanged("DiDong");
					this.OnDiDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(20)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_Thong_Tin_Lien_Lac_GV", Storage="_GiangVien", ThisKey="MaGV", OtherKey="MaGV", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.Thong_Tin_Lien_Lac_GV = null;
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Lien_Lac_GV = this;
						this._MaGV = value.MaGV;
					}
					else
					{
						this._MaGV = default(int);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thong_Tin_Lien_Lac")]
	public partial class Thong_Tin_Lien_Lac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _QuocGia;
		
		private string _TinhThanh;
		
		private string _QuanHuyen;
		
		private string _Phuong;
		
		private string _DiaChi;
		
		private string _DiDong;
		
		private string _Email;
		
		private EntityRef<Thong_Tin_Sinh_Vien> _Thong_Tin_Sinh_Vien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnQuocGiaChanging(string value);
    partial void OnQuocGiaChanged();
    partial void OnTinhThanhChanging(string value);
    partial void OnTinhThanhChanged();
    partial void OnQuanHuyenChanging(string value);
    partial void OnQuanHuyenChanged();
    partial void OnPhuongChanging(string value);
    partial void OnPhuongChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDiDongChanging(string value);
    partial void OnDiDongChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Thong_Tin_Lien_Lac()
		{
			this._Thong_Tin_Sinh_Vien = default(EntityRef<Thong_Tin_Sinh_Vien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					if (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocGia", DbType="NVarChar(20)")]
		public string QuocGia
		{
			get
			{
				return this._QuocGia;
			}
			set
			{
				if ((this._QuocGia != value))
				{
					this.OnQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._QuocGia = value;
					this.SendPropertyChanged("QuocGia");
					this.OnQuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhThanh", DbType="NVarChar(20)")]
		public string TinhThanh
		{
			get
			{
				return this._TinhThanh;
			}
			set
			{
				if ((this._TinhThanh != value))
				{
					this.OnTinhThanhChanging(value);
					this.SendPropertyChanging();
					this._TinhThanh = value;
					this.SendPropertyChanged("TinhThanh");
					this.OnTinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuanHuyen", DbType="NVarChar(20)")]
		public string QuanHuyen
		{
			get
			{
				return this._QuanHuyen;
			}
			set
			{
				if ((this._QuanHuyen != value))
				{
					this.OnQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._QuanHuyen = value;
					this.SendPropertyChanged("QuanHuyen");
					this.OnQuanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phuong", DbType="NVarChar(20)")]
		public string Phuong
		{
			get
			{
				return this._Phuong;
			}
			set
			{
				if ((this._Phuong != value))
				{
					this.OnPhuongChanging(value);
					this.SendPropertyChanging();
					this._Phuong = value;
					this.SendPropertyChanged("Phuong");
					this.OnPhuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiDong", DbType="NVarChar(20)")]
		public string DiDong
		{
			get
			{
				return this._DiDong;
			}
			set
			{
				if ((this._DiDong != value))
				{
					this.OnDiDongChanging(value);
					this.SendPropertyChanging();
					this._DiDong = value;
					this.SendPropertyChanged("DiDong");
					this.OnDiDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(20)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Thong_Tin_Lien_Lac", Storage="_Thong_Tin_Sinh_Vien", ThisKey="MaSV", OtherKey="MaSV", IsForeignKey=true)]
		public Thong_Tin_Sinh_Vien Thong_Tin_Sinh_Vien
		{
			get
			{
				return this._Thong_Tin_Sinh_Vien.Entity;
			}
			set
			{
				Thong_Tin_Sinh_Vien previousValue = this._Thong_Tin_Sinh_Vien.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Sinh_Vien.Entity = null;
						previousValue.Thong_Tin_Lien_Lac = null;
					}
					this._Thong_Tin_Sinh_Vien.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Lien_Lac = this;
						this._MaSV = value.MaSV;
					}
					else
					{
						this._MaSV = default(string);
					}
					this.SendPropertyChanged("Thong_Tin_Sinh_Vien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thong_Tin_Khoa_Hoc")]
	public partial class Thong_Tin_Khoa_Hoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _KhoaHoc;
		
		private System.DateTime _NgayNhapHoc;
		
		private string _LoaiHinhDaoTao;
		
		private string _ChuongTrinhDaoTao;
		
		private string _Khoa;
		
		private string _Nganh;
		
		private string _NienKhoa;
		
		private EntityRef<Thong_Tin_Sinh_Vien> _Thong_Tin_Sinh_Vien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnKhoaHocChanging(string value);
    partial void OnKhoaHocChanged();
    partial void OnNgayNhapHocChanging(System.DateTime value);
    partial void OnNgayNhapHocChanged();
    partial void OnLoaiHinhDaoTaoChanging(string value);
    partial void OnLoaiHinhDaoTaoChanged();
    partial void OnChuongTrinhDaoTaoChanging(string value);
    partial void OnChuongTrinhDaoTaoChanged();
    partial void OnKhoaChanging(string value);
    partial void OnKhoaChanged();
    partial void OnNganhChanging(string value);
    partial void OnNganhChanged();
    partial void OnNienKhoaChanging(string value);
    partial void OnNienKhoaChanged();
    #endregion
		
		public Thong_Tin_Khoa_Hoc()
		{
			this._Thong_Tin_Sinh_Vien = default(EntityRef<Thong_Tin_Sinh_Vien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					if (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoaHoc", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string KhoaHoc
		{
			get
			{
				return this._KhoaHoc;
			}
			set
			{
				if ((this._KhoaHoc != value))
				{
					this.OnKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._KhoaHoc = value;
					this.SendPropertyChanged("KhoaHoc");
					this.OnKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhapHoc", DbType="Date NOT NULL")]
		public System.DateTime NgayNhapHoc
		{
			get
			{
				return this._NgayNhapHoc;
			}
			set
			{
				if ((this._NgayNhapHoc != value))
				{
					this.OnNgayNhapHocChanging(value);
					this.SendPropertyChanging();
					this._NgayNhapHoc = value;
					this.SendPropertyChanged("NgayNhapHoc");
					this.OnNgayNhapHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHinhDaoTao", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string LoaiHinhDaoTao
		{
			get
			{
				return this._LoaiHinhDaoTao;
			}
			set
			{
				if ((this._LoaiHinhDaoTao != value))
				{
					this.OnLoaiHinhDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._LoaiHinhDaoTao = value;
					this.SendPropertyChanged("LoaiHinhDaoTao");
					this.OnLoaiHinhDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuongTrinhDaoTao", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ChuongTrinhDaoTao
		{
			get
			{
				return this._ChuongTrinhDaoTao;
			}
			set
			{
				if ((this._ChuongTrinhDaoTao != value))
				{
					this.OnChuongTrinhDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._ChuongTrinhDaoTao = value;
					this.SendPropertyChanged("ChuongTrinhDaoTao");
					this.OnChuongTrinhDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Khoa
		{
			get
			{
				return this._Khoa;
			}
			set
			{
				if ((this._Khoa != value))
				{
					this.OnKhoaChanging(value);
					this.SendPropertyChanging();
					this._Khoa = value;
					this.SendPropertyChanged("Khoa");
					this.OnKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nganh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Nganh
		{
			get
			{
				return this._Nganh;
			}
			set
			{
				if ((this._Nganh != value))
				{
					this.OnNganhChanging(value);
					this.SendPropertyChanging();
					this._Nganh = value;
					this.SendPropertyChanged("Nganh");
					this.OnNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NienKhoa", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NienKhoa
		{
			get
			{
				return this._NienKhoa;
			}
			set
			{
				if ((this._NienKhoa != value))
				{
					this.OnNienKhoaChanging(value);
					this.SendPropertyChanging();
					this._NienKhoa = value;
					this.SendPropertyChanged("NienKhoa");
					this.OnNienKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Thong_Tin_Khoa_Hoc", Storage="_Thong_Tin_Sinh_Vien", ThisKey="MaSV", OtherKey="MaSV", IsForeignKey=true)]
		public Thong_Tin_Sinh_Vien Thong_Tin_Sinh_Vien
		{
			get
			{
				return this._Thong_Tin_Sinh_Vien.Entity;
			}
			set
			{
				Thong_Tin_Sinh_Vien previousValue = this._Thong_Tin_Sinh_Vien.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Sinh_Vien.Entity = null;
						previousValue.Thong_Tin_Khoa_Hoc = null;
					}
					this._Thong_Tin_Sinh_Vien.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Khoa_Hoc = this;
						this._MaSV = value.MaSV;
					}
					else
					{
						this._MaSV = default(string);
					}
					this.SendPropertyChanged("Thong_Tin_Sinh_Vien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _LoaiNguoiDung;
		
		private string _MaNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnLoaiNguoiDungChanging(string value);
    partial void OnLoaiNguoiDungChanged();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNguoiDung", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string LoaiNguoiDung
		{
			get
			{
				return this._LoaiNguoiDung;
			}
			set
			{
				if ((this._LoaiNguoiDung != value))
				{
					this.OnLoaiNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._LoaiNguoiDung = value;
					this.SendPropertyChanged("LoaiNguoiDung");
					this.OnLoaiNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongHoc")]
	public partial class PhongHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhong;
		
		private int _SucChua;
		
		private string _LoaiPhong;
		
		private int _GiangVienPhuTrach;
		
		private int _TietBatDau;
		
		private int _TietKetThuc;
		
		private EntityRef<GiangVien> _GiangVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnSucChuaChanging(int value);
    partial void OnSucChuaChanged();
    partial void OnLoaiPhongChanging(string value);
    partial void OnLoaiPhongChanged();
    partial void OnGiangVienPhuTrachChanging(int value);
    partial void OnGiangVienPhuTrachChanged();
    partial void OnTietBatDauChanging(int value);
    partial void OnTietBatDauChanged();
    partial void OnTietKetThucChanging(int value);
    partial void OnTietKetThucChanged();
    #endregion
		
		public PhongHoc()
		{
			this._GiangVien = default(EntityRef<GiangVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucChua", DbType="Int NOT NULL")]
		public int SucChua
		{
			get
			{
				return this._SucChua;
			}
			set
			{
				if ((this._SucChua != value))
				{
					this.OnSucChuaChanging(value);
					this.SendPropertyChanging();
					this._SucChua = value;
					this.SendPropertyChanged("SucChua");
					this.OnSucChuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPhong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiPhong
		{
			get
			{
				return this._LoaiPhong;
			}
			set
			{
				if ((this._LoaiPhong != value))
				{
					this.OnLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._LoaiPhong = value;
					this.SendPropertyChanged("LoaiPhong");
					this.OnLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiangVienPhuTrach", DbType="Int NOT NULL")]
		public int GiangVienPhuTrach
		{
			get
			{
				return this._GiangVienPhuTrach;
			}
			set
			{
				if ((this._GiangVienPhuTrach != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGiangVienPhuTrachChanging(value);
					this.SendPropertyChanging();
					this._GiangVienPhuTrach = value;
					this.SendPropertyChanged("GiangVienPhuTrach");
					this.OnGiangVienPhuTrachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TietBatDau", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TietBatDau
		{
			get
			{
				return this._TietBatDau;
			}
			set
			{
				if ((this._TietBatDau != value))
				{
					this.OnTietBatDauChanging(value);
					this.SendPropertyChanging();
					this._TietBatDau = value;
					this.SendPropertyChanged("TietBatDau");
					this.OnTietBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TietKetThuc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TietKetThuc
		{
			get
			{
				return this._TietKetThuc;
			}
			set
			{
				if ((this._TietKetThuc != value))
				{
					this.OnTietKetThucChanging(value);
					this.SendPropertyChanging();
					this._TietKetThuc = value;
					this.SendPropertyChanged("TietKetThuc");
					this.OnTietKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_PhongHoc", Storage="_GiangVien", ThisKey="GiangVienPhuTrach", OtherKey="MaGV", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.PhongHocs.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.PhongHocs.Add(this);
						this._GiangVienPhuTrach = value.MaGV;
					}
					else
					{
						this._GiangVienPhuTrach = default(int);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonHoc")]
	public partial class MonHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMonHoc;
		
		private string _TenMonHoc;
		
		private int _SoTinChi;
		
		private string _MaKhoa;
		
		private int _SoTiet;
		
		private string _LoaiMon;
		
		private EntitySet<Diem> _Diems;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMonHocChanging(string value);
    partial void OnMaMonHocChanged();
    partial void OnTenMonHocChanging(string value);
    partial void OnTenMonHocChanged();
    partial void OnSoTinChiChanging(int value);
    partial void OnSoTinChiChanged();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnSoTietChanging(int value);
    partial void OnSoTietChanged();
    partial void OnLoaiMonChanging(string value);
    partial void OnLoaiMonChanged();
    #endregion
		
		public MonHoc()
		{
			this._Diems = new EntitySet<Diem>(new Action<Diem>(this.attach_Diems), new Action<Diem>(this.detach_Diems));
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMonHoc", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMonHoc
		{
			get
			{
				return this._MaMonHoc;
			}
			set
			{
				if ((this._MaMonHoc != value))
				{
					this.OnMaMonHocChanging(value);
					this.SendPropertyChanging();
					this._MaMonHoc = value;
					this.SendPropertyChanged("MaMonHoc");
					this.OnMaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMonHoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenMonHoc
		{
			get
			{
				return this._TenMonHoc;
			}
			set
			{
				if ((this._TenMonHoc != value))
				{
					this.OnTenMonHocChanging(value);
					this.SendPropertyChanging();
					this._TenMonHoc = value;
					this.SendPropertyChanged("TenMonHoc");
					this.OnTenMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTinChi", DbType="Int NOT NULL")]
		public int SoTinChi
		{
			get
			{
				return this._SoTinChi;
			}
			set
			{
				if ((this._SoTinChi != value))
				{
					this.OnSoTinChiChanging(value);
					this.SendPropertyChanging();
					this._SoTinChi = value;
					this.SendPropertyChanged("SoTinChi");
					this.OnSoTinChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTiet", DbType="Int NOT NULL")]
		public int SoTiet
		{
			get
			{
				return this._SoTiet;
			}
			set
			{
				if ((this._SoTiet != value))
				{
					this.OnSoTietChanging(value);
					this.SendPropertyChanging();
					this._SoTiet = value;
					this.SendPropertyChanged("SoTiet");
					this.OnSoTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiMon
		{
			get
			{
				return this._LoaiMon;
			}
			set
			{
				if ((this._LoaiMon != value))
				{
					this.OnLoaiMonChanging(value);
					this.SendPropertyChanging();
					this._LoaiMon = value;
					this.SendPropertyChanged("LoaiMon");
					this.OnLoaiMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_Diem", Storage="_Diems", ThisKey="MaMonHoc", OtherKey="MaMonHoc")]
		public EntitySet<Diem> Diems
		{
			get
			{
				return this._Diems;
			}
			set
			{
				this._Diems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_MonHoc", Storage="_Khoa", ThisKey="MaKhoa", OtherKey="MaKhoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.MonHocs.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.MonHocs.Add(this);
						this._MaKhoa = value.MaKhoa;
					}
					else
					{
						this._MaKhoa = default(string);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = this;
		}
		
		private void detach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lop")]
	public partial class Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLop;
		
		private string _TenLop;
		
		private string _MaKhoa;
		
		private EntitySet<Thong_Tin_Sinh_Vien> _Thong_Tin_Sinh_Viens;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnTenLopChanging(string value);
    partial void OnTenLopChanged();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    #endregion
		
		public Lop()
		{
			this._Thong_Tin_Sinh_Viens = new EntitySet<Thong_Tin_Sinh_Vien>(new Action<Thong_Tin_Sinh_Vien>(this.attach_Thong_Tin_Sinh_Viens), new Action<Thong_Tin_Sinh_Vien>(this.detach_Thong_Tin_Sinh_Viens));
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this.OnTenLopChanging(value);
					this.SendPropertyChanging();
					this._TenLop = value;
					this.SendPropertyChanged("TenLop");
					this.OnTenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10)")]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_Thong_Tin_Sinh_Vien", Storage="_Thong_Tin_Sinh_Viens", ThisKey="MaLop", OtherKey="LopSV")]
		public EntitySet<Thong_Tin_Sinh_Vien> Thong_Tin_Sinh_Viens
		{
			get
			{
				return this._Thong_Tin_Sinh_Viens;
			}
			set
			{
				this._Thong_Tin_Sinh_Viens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_Lop", Storage="_Khoa", ThisKey="MaKhoa", OtherKey="MaKhoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.Lops.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.Lops.Add(this);
						this._MaKhoa = value.MaKhoa;
					}
					else
					{
						this._MaKhoa = default(string);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thong_Tin_Sinh_Viens(Thong_Tin_Sinh_Vien entity)
		{
			this.SendPropertyChanging();
			entity.Lop = this;
		}
		
		private void detach_Thong_Tin_Sinh_Viens(Thong_Tin_Sinh_Vien entity)
		{
			this.SendPropertyChanging();
			entity.Lop = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoa")]
	public partial class Khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhoa;
		
		private string _TenKhoa;
		
		private EntitySet<MonHoc> _MonHocs;
		
		private EntitySet<Lop> _Lops;
		
		private EntitySet<GiangVien> _GiangViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnTenKhoaChanging(string value);
    partial void OnTenKhoaChanged();
    #endregion
		
		public Khoa()
		{
			this._MonHocs = new EntitySet<MonHoc>(new Action<MonHoc>(this.attach_MonHocs), new Action<MonHoc>(this.detach_MonHocs));
			this._Lops = new EntitySet<Lop>(new Action<Lop>(this.attach_Lops), new Action<Lop>(this.detach_Lops));
			this._GiangViens = new EntitySet<GiangVien>(new Action<GiangVien>(this.attach_GiangViens), new Action<GiangVien>(this.detach_GiangViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoa", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKhoa
		{
			get
			{
				return this._TenKhoa;
			}
			set
			{
				if ((this._TenKhoa != value))
				{
					this.OnTenKhoaChanging(value);
					this.SendPropertyChanging();
					this._TenKhoa = value;
					this.SendPropertyChanged("TenKhoa");
					this.OnTenKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_MonHoc", Storage="_MonHocs", ThisKey="MaKhoa", OtherKey="MaKhoa")]
		public EntitySet<MonHoc> MonHocs
		{
			get
			{
				return this._MonHocs;
			}
			set
			{
				this._MonHocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_Lop", Storage="_Lops", ThisKey="MaKhoa", OtherKey="MaKhoa")]
		public EntitySet<Lop> Lops
		{
			get
			{
				return this._Lops;
			}
			set
			{
				this._Lops.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_GiangVien", Storage="_GiangViens", ThisKey="MaKhoa", OtherKey="MaKhoa")]
		public EntitySet<GiangVien> GiangViens
		{
			get
			{
				return this._GiangViens;
			}
			set
			{
				this._GiangViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MonHocs(MonHoc entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_MonHocs(MonHoc entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
		
		private void attach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
		
		private void attach_GiangViens(GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_GiangViens(GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Diem")]
	public partial class Diem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MaSV;
		
		private string _MaMonHoc;
		
		private System.Nullable<int> _PhanTramTrenLop;
		
		private System.Nullable<int> _PhanTramThi;
		
		private System.Nullable<double> _DiemTrenLop;
		
		private System.Nullable<double> _DiemThi;
		
		private System.Nullable<double> _DiemTB;
		
		private System.Nullable<char> _Loai;
		
		private EntityRef<MonHoc> _MonHoc;
		
		private EntityRef<Thong_Tin_Sinh_Vien> _Thong_Tin_Sinh_Vien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnMaMonHocChanging(string value);
    partial void OnMaMonHocChanged();
    partial void OnPhanTramTrenLopChanging(System.Nullable<int> value);
    partial void OnPhanTramTrenLopChanged();
    partial void OnPhanTramThiChanging(System.Nullable<int> value);
    partial void OnPhanTramThiChanged();
    partial void OnDiemTrenLopChanging(System.Nullable<double> value);
    partial void OnDiemTrenLopChanged();
    partial void OnDiemThiChanging(System.Nullable<double> value);
    partial void OnDiemThiChanged();
    partial void OnDiemTBChanging(System.Nullable<double> value);
    partial void OnDiemTBChanged();
    partial void OnLoaiChanging(System.Nullable<char> value);
    partial void OnLoaiChanged();
    #endregion
		
		public Diem()
		{
			this._MonHoc = default(EntityRef<MonHoc>);
			this._Thong_Tin_Sinh_Vien = default(EntityRef<Thong_Tin_Sinh_Vien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					if (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMonHoc", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaMonHoc
		{
			get
			{
				return this._MaMonHoc;
			}
			set
			{
				if ((this._MaMonHoc != value))
				{
					if (this._MonHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonHocChanging(value);
					this.SendPropertyChanging();
					this._MaMonHoc = value;
					this.SendPropertyChanged("MaMonHoc");
					this.OnMaMonHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanTramTrenLop", DbType="Int")]
		public System.Nullable<int> PhanTramTrenLop
		{
			get
			{
				return this._PhanTramTrenLop;
			}
			set
			{
				if ((this._PhanTramTrenLop != value))
				{
					this.OnPhanTramTrenLopChanging(value);
					this.SendPropertyChanging();
					this._PhanTramTrenLop = value;
					this.SendPropertyChanged("PhanTramTrenLop");
					this.OnPhanTramTrenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanTramThi", DbType="Int")]
		public System.Nullable<int> PhanTramThi
		{
			get
			{
				return this._PhanTramThi;
			}
			set
			{
				if ((this._PhanTramThi != value))
				{
					this.OnPhanTramThiChanging(value);
					this.SendPropertyChanging();
					this._PhanTramThi = value;
					this.SendPropertyChanged("PhanTramThi");
					this.OnPhanTramThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemTrenLop", DbType="Float")]
		public System.Nullable<double> DiemTrenLop
		{
			get
			{
				return this._DiemTrenLop;
			}
			set
			{
				if ((this._DiemTrenLop != value))
				{
					this.OnDiemTrenLopChanging(value);
					this.SendPropertyChanging();
					this._DiemTrenLop = value;
					this.SendPropertyChanged("DiemTrenLop");
					this.OnDiemTrenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemThi", DbType="Float")]
		public System.Nullable<double> DiemThi
		{
			get
			{
				return this._DiemThi;
			}
			set
			{
				if ((this._DiemThi != value))
				{
					this.OnDiemThiChanging(value);
					this.SendPropertyChanging();
					this._DiemThi = value;
					this.SendPropertyChanged("DiemThi");
					this.OnDiemThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemTB", DbType="Float")]
		public System.Nullable<double> DiemTB
		{
			get
			{
				return this._DiemTB;
			}
			set
			{
				if ((this._DiemTB != value))
				{
					this.OnDiemTBChanging(value);
					this.SendPropertyChanging();
					this._DiemTB = value;
					this.SendPropertyChanged("DiemTB");
					this.OnDiemTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="Char(1)")]
		public System.Nullable<char> Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_Diem", Storage="_MonHoc", ThisKey="MaMonHoc", OtherKey="MaMonHoc", IsForeignKey=true)]
		public MonHoc MonHoc
		{
			get
			{
				return this._MonHoc.Entity;
			}
			set
			{
				MonHoc previousValue = this._MonHoc.Entity;
				if (((previousValue != value) 
							|| (this._MonHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonHoc.Entity = null;
						previousValue.Diems.Remove(this);
					}
					this._MonHoc.Entity = value;
					if ((value != null))
					{
						value.Diems.Add(this);
						this._MaMonHoc = value.MaMonHoc;
					}
					else
					{
						this._MaMonHoc = default(string);
					}
					this.SendPropertyChanged("MonHoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Diem", Storage="_Thong_Tin_Sinh_Vien", ThisKey="MaSV", OtherKey="MaSV", IsForeignKey=true)]
		public Thong_Tin_Sinh_Vien Thong_Tin_Sinh_Vien
		{
			get
			{
				return this._Thong_Tin_Sinh_Vien.Entity;
			}
			set
			{
				Thong_Tin_Sinh_Vien previousValue = this._Thong_Tin_Sinh_Vien.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Sinh_Vien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Sinh_Vien.Entity = null;
						previousValue.Diems.Remove(this);
					}
					this._Thong_Tin_Sinh_Vien.Entity = value;
					if ((value != null))
					{
						value.Diems.Add(this);
						this._MaSV = value.MaSV;
					}
					else
					{
						this._MaSV = default(string);
					}
					this.SendPropertyChanged("Thong_Tin_Sinh_Vien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thong_Tin_Sinh_Vien")]
	public partial class Thong_Tin_Sinh_Vien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private string _NoiSinh;
		
		private string _GioiTinh;
		
		private string _CCCD;
		
		private string _DanToc;
		
		private string _LopSV;
		
		private System.Data.Linq.Binary _Photo;
		
		private string _MatKhau;
		
		private EntitySet<Thong_Tin_Nguoi_LH> _Thong_Tin_Nguoi_LHs;
		
		private EntityRef<Thong_Tin_Lien_Lac> _Thong_Tin_Lien_Lac;
		
		private EntityRef<Thong_Tin_Khoa_Hoc> _Thong_Tin_Khoa_Hoc;
		
		private EntitySet<Diem> _Diems;
		
		private EntityRef<Lop> _Lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnNoiSinhChanging(string value);
    partial void OnNoiSinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnLopSVChanging(string value);
    partial void OnLopSVChanged();
    partial void OnPhotoChanging(System.Data.Linq.Binary value);
    partial void OnPhotoChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public Thong_Tin_Sinh_Vien()
		{
			this._Thong_Tin_Nguoi_LHs = new EntitySet<Thong_Tin_Nguoi_LH>(new Action<Thong_Tin_Nguoi_LH>(this.attach_Thong_Tin_Nguoi_LHs), new Action<Thong_Tin_Nguoi_LH>(this.detach_Thong_Tin_Nguoi_LHs));
			this._Thong_Tin_Lien_Lac = default(EntityRef<Thong_Tin_Lien_Lac>);
			this._Thong_Tin_Khoa_Hoc = default(EntityRef<Thong_Tin_Khoa_Hoc>);
			this._Diems = new EntitySet<Diem>(new Action<Diem>(this.attach_Diems), new Action<Diem>(this.detach_Diems));
			this._Lop = default(EntityRef<Lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this.OnNoiSinhChanging(value);
					this.SendPropertyChanging();
					this._NoiSinh = value;
					this.SendPropertyChanged("NoiSinh");
					this.OnNoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LopSV", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string LopSV
		{
			get
			{
				return this._LopSV;
			}
			set
			{
				if ((this._LopSV != value))
				{
					if (this._Lop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLopSVChanging(value);
					this.SendPropertyChanging();
					this._LopSV = value;
					this.SendPropertyChanged("LopSV");
					this.OnLopSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(20)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Thong_Tin_Nguoi_LH", Storage="_Thong_Tin_Nguoi_LHs", ThisKey="MaSV", OtherKey="MaSV")]
		public EntitySet<Thong_Tin_Nguoi_LH> Thong_Tin_Nguoi_LHs
		{
			get
			{
				return this._Thong_Tin_Nguoi_LHs;
			}
			set
			{
				this._Thong_Tin_Nguoi_LHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Thong_Tin_Lien_Lac", Storage="_Thong_Tin_Lien_Lac", ThisKey="MaSV", OtherKey="MaSV", IsUnique=true, IsForeignKey=false)]
		public Thong_Tin_Lien_Lac Thong_Tin_Lien_Lac
		{
			get
			{
				return this._Thong_Tin_Lien_Lac.Entity;
			}
			set
			{
				Thong_Tin_Lien_Lac previousValue = this._Thong_Tin_Lien_Lac.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Lien_Lac.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Lien_Lac.Entity = null;
						previousValue.Thong_Tin_Sinh_Vien = null;
					}
					this._Thong_Tin_Lien_Lac.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Sinh_Vien = this;
					}
					this.SendPropertyChanged("Thong_Tin_Lien_Lac");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Thong_Tin_Khoa_Hoc", Storage="_Thong_Tin_Khoa_Hoc", ThisKey="MaSV", OtherKey="MaSV", IsUnique=true, IsForeignKey=false)]
		public Thong_Tin_Khoa_Hoc Thong_Tin_Khoa_Hoc
		{
			get
			{
				return this._Thong_Tin_Khoa_Hoc.Entity;
			}
			set
			{
				Thong_Tin_Khoa_Hoc previousValue = this._Thong_Tin_Khoa_Hoc.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Khoa_Hoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Khoa_Hoc.Entity = null;
						previousValue.Thong_Tin_Sinh_Vien = null;
					}
					this._Thong_Tin_Khoa_Hoc.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Sinh_Vien = this;
					}
					this.SendPropertyChanged("Thong_Tin_Khoa_Hoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thong_Tin_Sinh_Vien_Diem", Storage="_Diems", ThisKey="MaSV", OtherKey="MaSV")]
		public EntitySet<Diem> Diems
		{
			get
			{
				return this._Diems;
			}
			set
			{
				this._Diems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_Thong_Tin_Sinh_Vien", Storage="_Lop", ThisKey="LopSV", OtherKey="MaLop", IsForeignKey=true)]
		public Lop Lop
		{
			get
			{
				return this._Lop.Entity;
			}
			set
			{
				Lop previousValue = this._Lop.Entity;
				if (((previousValue != value) 
							|| (this._Lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lop.Entity = null;
						previousValue.Thong_Tin_Sinh_Viens.Remove(this);
					}
					this._Lop.Entity = value;
					if ((value != null))
					{
						value.Thong_Tin_Sinh_Viens.Add(this);
						this._LopSV = value.MaLop;
					}
					else
					{
						this._LopSV = default(string);
					}
					this.SendPropertyChanged("Lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thong_Tin_Nguoi_LHs(Thong_Tin_Nguoi_LH entity)
		{
			this.SendPropertyChanging();
			entity.Thong_Tin_Sinh_Vien = this;
		}
		
		private void detach_Thong_Tin_Nguoi_LHs(Thong_Tin_Nguoi_LH entity)
		{
			this.SendPropertyChanging();
			entity.Thong_Tin_Sinh_Vien = null;
		}
		
		private void attach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.Thong_Tin_Sinh_Vien = this;
		}
		
		private void detach_Diems(Diem entity)
		{
			this.SendPropertyChanging();
			entity.Thong_Tin_Sinh_Vien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiangVien")]
	public partial class GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGV;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private string _MaKhoa;
		
		private string _DienThoai;
		
		private string _Email;
		
		private string _SoDienThoai;
		
		private string _CCCD;
		
		private string _DanToc;
		
		private string _NoiSinh;
		
		private string _MatKhau;
		
		private EntityRef<Thong_Tin_Nguoi_LH_GV> _Thong_Tin_Nguoi_LH_GV;
		
		private EntityRef<Thong_Tin_Lien_Lac_GV> _Thong_Tin_Lien_Lac_GV;
		
		private EntitySet<PhongHoc> _PhongHocs;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGVChanging(int value);
    partial void OnMaGVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnNoiSinhChanging(string value);
    partial void OnNoiSinhChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public GiangVien()
		{
			this._Thong_Tin_Nguoi_LH_GV = default(EntityRef<Thong_Tin_Nguoi_LH_GV>);
			this._Thong_Tin_Lien_Lac_GV = default(EntityRef<Thong_Tin_Lien_Lac_GV>);
			this._PhongHocs = new EntitySet<PhongHoc>(new Action<PhongHoc>(this.attach_PhongHocs), new Action<PhongHoc>(this.detach_PhongHocs));
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaGV
		{
			get
			{
				return this._MaGV;
			}
			set
			{
				if ((this._MaGV != value))
				{
					this.OnMaGVChanging(value);
					this.SendPropertyChanging();
					this._MaGV = value;
					this.SendPropertyChanged("MaGV");
					this.OnMaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(10)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NVarChar(20)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(20)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(50)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this.OnNoiSinhChanging(value);
					this.SendPropertyChanging();
					this._NoiSinh = value;
					this.SendPropertyChanged("NoiSinh");
					this.OnNoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(20)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_Thong_Tin_Nguoi_LH_GV", Storage="_Thong_Tin_Nguoi_LH_GV", ThisKey="MaGV", OtherKey="MaGV", IsUnique=true, IsForeignKey=false)]
		public Thong_Tin_Nguoi_LH_GV Thong_Tin_Nguoi_LH_GV
		{
			get
			{
				return this._Thong_Tin_Nguoi_LH_GV.Entity;
			}
			set
			{
				Thong_Tin_Nguoi_LH_GV previousValue = this._Thong_Tin_Nguoi_LH_GV.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Nguoi_LH_GV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Nguoi_LH_GV.Entity = null;
						previousValue.GiangVien = null;
					}
					this._Thong_Tin_Nguoi_LH_GV.Entity = value;
					if ((value != null))
					{
						value.GiangVien = this;
					}
					this.SendPropertyChanged("Thong_Tin_Nguoi_LH_GV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_Thong_Tin_Lien_Lac_GV", Storage="_Thong_Tin_Lien_Lac_GV", ThisKey="MaGV", OtherKey="MaGV", IsUnique=true, IsForeignKey=false)]
		public Thong_Tin_Lien_Lac_GV Thong_Tin_Lien_Lac_GV
		{
			get
			{
				return this._Thong_Tin_Lien_Lac_GV.Entity;
			}
			set
			{
				Thong_Tin_Lien_Lac_GV previousValue = this._Thong_Tin_Lien_Lac_GV.Entity;
				if (((previousValue != value) 
							|| (this._Thong_Tin_Lien_Lac_GV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thong_Tin_Lien_Lac_GV.Entity = null;
						previousValue.GiangVien = null;
					}
					this._Thong_Tin_Lien_Lac_GV.Entity = value;
					if ((value != null))
					{
						value.GiangVien = this;
					}
					this.SendPropertyChanged("Thong_Tin_Lien_Lac_GV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_PhongHoc", Storage="_PhongHocs", ThisKey="MaGV", OtherKey="GiangVienPhuTrach")]
		public EntitySet<PhongHoc> PhongHocs
		{
			get
			{
				return this._PhongHocs;
			}
			set
			{
				this._PhongHocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_GiangVien", Storage="_Khoa", ThisKey="MaKhoa", OtherKey="MaKhoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.GiangViens.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.GiangViens.Add(this);
						this._MaKhoa = value.MaKhoa;
					}
					else
					{
						this._MaKhoa = default(string);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhongHocs(PhongHoc entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_PhongHocs(PhongHoc entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
	}
}
#pragma warning restore 1591
